name = "AndorCameras"
uuid = "a6f1060a-fcb4-4ec9-a17b-f0f9a1d7da62"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr>"]
version = "0.2.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ScientificCameras = "c7119640-a72f-41a6-aa41-758559b204e7"
